on:
  push:
    branches: master
name: Pkgdown
jobs:
  pkgdown:
    runs-on: ubuntu-16.04
    container:
      image: egruw/qe-pkgdown:latest
    steps:
      - uses: actions/checkout@master
      - name: Query dependencies
        run: Rscript -e "install.packages('remotes')" -e "saveRDS(remotes::dev_package_deps(dependencies = TRUE), 'depends.Rds', version = 2)"
      #- name: Cache R packages
      #  if: runner.os != 'Windows'
      #  uses: actions/cache@v1
      #  with:
      #    path: ${{ env.R_LIBS_USER }}
      #    key: ${{ runner.os }}-r-${{ matrix.config.r }}-${{ hashFiles('depends.Rds') }}
      #    restore-keys: ${{ runner.os }}-r-${{ matrix.config.r }}-
      - name: Install system dependencies
        if: runner.os == 'Linux'
        env:
          RHUB_PLATFORM: linux-x86_64-ubuntu-gcc
        run: |
          Rscript -e "remotes::install_github('r-hub/sysreqs')"
          sysreqs=$(Rscript -e "cat(sysreqs::sysreq_commands('DESCRIPTION'))")
          sudo -s eval "$sysreqs"
      - name: Install dependencies
        run: Rscript -e "library(remotes)" -e "update(readRDS('depends.Rds'))" -e "remotes::install_cran('rcmdcheck')"
      - name: Install package
        run: R CMD INSTALL .
      - name: Configure git
        run: |
          git config --global user.name runner
          git config --global user.email runner
          git config http.https://github.com/.extraheader "AUTHORIZATION: basic ${{ secrets.GITHUB_TOKEN }}"
      - name: Deploy package
        run: |
          pkgdown:::deploy_local(new_process = FALSE, remote_url = 'https://x-access-token:${{secrets.DEPLOY_PAT}}@github.com/${{github.repository}}.git');
        shell: Rscript {0}
      #- name: Deploy package
      #  run: pkgdown::deploy_to_branch(new_process = FALSE)
      #  shell: Rscript {0}
      - name: Test coverage
        run: |
          Rscript -e 'install.packages(c("covr"))' \
                  -e 'dest_dir=fs::dir_create(fs::file_temp()); on.exit(fs::dir_delete(dest_dir)); clnd=pkgdown:::git( "clone", "--single-branch", "-b", "gh-pages", "--depth", "1", "https://x-access-token:${{secrets.DEPLOY_PAT}}@github.com/codymarquart/shinyLogger.git", dest_dir ); covr::report(file = paste0(dest_dir, "/coverage/index.html")); pkgdown:::github_push(dest_dir, pkgdown:::construct_commit_message("."));'

